# Generated by Django 5.0.4 on 2024-06-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_post_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='nomi',
        ),
    ]
